### PR TITLE
C++ spline generation

### PR DESCRIPTION
**Pull request by tkoolen**
Alright, I went a bit overboard with this... I should probably move the spline generation / piecewise polynomial handling C++ code to a different folder since it's pretty general and pull request it with RobotLocomotion Drake. But I wanted to show you what I have now.

I wrote simple Polynomial and PiecewisePolynomial classes and a splineGeneration method that can generate a spline with any number of segments, where the segment polynomials can have any (and varying) order. It does this based on a set of constraints you give it. Currently I've implemented `ValueConstraint` (constraint on function value or value of one of its derivatives at a certain time) and `ContinuityConstraint` (continuity of function or one of its derivatives between spline segments). The `generateSpline` method currently only handles the case where there is a single solution.

I created mex functions that call the `generateSpline function` underneath, but the Matlab implementation is currently faster than C++... There are things I can improve, but it's going to be a struggle to become faster than Matlab.

BTW, I was using your Matlab implementation for a mex/Matlab comparison, so I added it back in.

So do you want to accept this, or should I pull request it separately with RobotLocomotion Drake?

### CODE REVIEW

**Comment by tkoolen** [comment]
I profiled things. One call to twoWaypointCubicSpline (resulting in a 1D spline) takes about 5.3 microseconds from C++ (no Matlab involved).
In Matlab, running testqpSpline (i.e. asking for a 6D spline) without mex is about 16 microseconds (i.e. already less than 6 times the pure C version), whereas a call with mex is 124 microseconds. So there's a lot of mex overhead or work time being spent in the mex function, but even if that were to go away it's still not faster than Matlab.

**Comment by rdeits** [comment]
This is really cool! Also, I'm actually showing your mex version to be much faster! The problem is that matlab's `timeit` uses `tic()` and `toc()`, which share a *global* variable for the start time. But my matlab spline implementation also has a `tic()` and `toc()` in it, which totally screws up the global start time used by timeit. As far as I can tell, that means that `timeit` will just always give garbage if your function happens to contain a call to `tic()`. 

Anyway, with that removed, I show mex at 140 microseconds for a 6D spline and Matlab at 680 microseconds, which is great news for your code :)

**Comment by rdeits** [comment]
And your new free knot point optimization is ~1.7ms, which should definitely be fast enough. I'll merge this in and test it out in sim tomorrow.

**Comment by tkoolen** [comment]
See https://github.com/RobotLocomotion/drake/pull/972. I took my branch, which was based off of 4974f0e54e8ba40073a07f3b13531c2379bf3eab, and rebased it onto master.

I fixed that bug in computing the objective value *after* rebasing my changes; my PiecewisePolynomial integral function was wrong. Got rid of the Q matrix computation after fixing that and verifying that the result is the same and that it's just as fast. Also updated some tests.

Let me know if you need help merging once it's all in.

**Pull request merged**
